#!/usr/bin/env python3
"""Generate a self-contained HTML report from benchmark results.

Reads aggregated results and individual grade files, produces a single
HTML file with inline CSS — no external dependencies.

Targets Python 3.8+ with no external dependencies beyond stdlib.
"""

import argparse
import glob
import json
import os
import sys
import time

DIMENSIONS = ["structure", "completeness", "quality"]

HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Skill Eval Report: {skill_name}</title>
<style>
  :root {{
    --pass: #16a34a;
    --fail: #dc2626;
    --bg: #f8fafc;
    --card: #ffffff;
    --border: #e2e8f0;
    --text: #1e293b;
    --muted: #64748b;
  }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                 "Helvetica Neue", Arial, sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.6;
    padding: 2rem;
  }}
  .container {{ max-width: 720px; margin: 0 auto; }}
  h1 {{ font-size: 1.5rem; margin-bottom: 0.25rem; }}
  .subtitle {{ color: var(--muted); font-size: 0.875rem; margin-bottom: 2rem; }}
  .verdict {{
    display: inline-block;
    padding: 0.375rem 1rem;
    border-radius: 6px;
    font-weight: 700;
    font-size: 1.125rem;
    margin-bottom: 1.5rem;
  }}
  .verdict.pass {{ background: #dcfce7; color: var(--pass); }}
  .verdict.fail {{ background: #fef2f2; color: var(--fail); }}
  .card {{
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.25rem;
    margin-bottom: 1rem;
  }}
  .card h2 {{
    font-size: 1rem;
    margin-bottom: 0.75rem;
    color: var(--muted);
    text-transform: uppercase;
    letter-spacing: 0.05em;
  }}
  table {{ width: 100%; border-collapse: collapse; }}
  th, td {{
    text-align: left;
    padding: 0.5rem 0.75rem;
    border-bottom: 1px solid var(--border);
  }}
  th {{ font-weight: 600; font-size: 0.8125rem; color: var(--muted); }}
  td {{ font-size: 0.875rem; }}
  .score {{ font-weight: 600; font-variant-numeric: tabular-nums; }}
  .indicator {{ font-size: 1rem; }}
  .pass-indicator {{ color: var(--pass); }}
  .fail-indicator {{ color: var(--fail); }}
  .meta {{ font-size: 0.75rem; color: var(--muted); margin-top: 2rem; text-align: center; }}
</style>
</head>
<body>
<div class="container">
  <h1>Skill Eval: {skill_name}</h1>
  <div class="subtitle">Evaluated {eval_date} &middot; {total_runs} run(s)</div>

  <div class="verdict {verdict_class}">
    {verdict_indicator} {verdict}
  </div>

  <div class="card">
    <h2>Overall Scores</h2>
    <table>
      <thead>
        <tr>
          <th>Dimension</th>
          <th>Mean</th>
          <th>Std Dev</th>
          <th>Min</th>
          <th>Max</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
{dimension_rows}
        <tr style="border-top: 2px solid var(--border);">
          <td><strong>Overall</strong></td>
          <td class="score"><strong>{overall_mean}</strong></td>
          <td colspan="3"></td>
          <td class="indicator">{overall_indicator}</td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="card">
    <h2>Per-Run Breakdown</h2>
    <table>
      <thead>
        <tr>
          <th>Run</th>
{per_run_headers}
          <th>Mean</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
{per_run_rows}
      </tbody>
    </table>
  </div>

  <div class="meta">
    Generated by skill-review-standard eval tooling &middot; Threshold: {threshold}
  </div>
</div>
</body>
</html>
"""


def load_aggregated(results_dir):
    """Load aggregated results. Try aggregate.json first, then compute."""
    # Look for pre-computed aggregate
    for name in ("aggregate.json", "aggregated.json", "results.json"):
        path = os.path.join(results_dir, name)
        if os.path.isfile(path):
            with open(path, encoding="utf-8") as f:
                return json.load(f)

    # No aggregate found — try to compute from grade files on the fly
    # Import aggregate_benchmark inline to avoid circular deps
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from aggregate_benchmark import load_grade_files, aggregate

    grades = load_grade_files(results_dir)
    if not grades:
        return None
    return aggregate(grades)


def indicator(passed):
    """Return a pass/fail indicator character and CSS class."""
    if passed:
        return "&#10003;", "pass-indicator"
    return "&#10007;", "fail-indicator"


def build_dimension_rows(dim_stats, threshold):
    """Build HTML table rows for each scoring dimension."""
    rows = []
    for dim in DIMENSIONS:
        stats = dim_stats.get(dim, {})
        mean = stats.get("mean", 0)
        stddev = stats.get("stddev", 0)
        mn = stats.get("min", 0)
        mx = stats.get("max", 0)
        passed = mean >= threshold
        char, cls = indicator(passed)
        rows.append(
            f"        <tr>\n"
            f'          <td>{dim.capitalize()}</td>\n'
            f'          <td class="score">{mean}</td>\n'
            f"          <td>{stddev}</td>\n"
            f"          <td>{mn}</td>\n"
            f"          <td>{mx}</td>\n"
            f'          <td class="indicator {cls}">{char}</td>\n'
            f"        </tr>"
        )
    return "\n".join(rows)


def build_per_run_rows(per_run, threshold):
    """Build HTML table rows for per-run breakdown."""
    headers = ""
    for dim in DIMENSIONS:
        headers += f"          <th>{dim.capitalize()}</th>\n"

    rows = []
    for entry in per_run:
        run_label = entry.get("file", "").replace("_grade.json", "").replace("_", " ")
        scores = entry.get("scores", {})
        mean = entry.get("mean", 0)
        passed = mean >= threshold
        char, cls = indicator(passed)

        cells = f'          <td>{run_label}</td>\n'
        for dim in DIMENSIONS:
            score = scores.get(dim, "—")
            cells += f'          <td class="score">{score}</td>\n'
        cells += f'          <td class="score">{mean}</td>\n'
        cells += f'          <td class="indicator {cls}">{char}</td>'

        rows.append(f"        <tr>\n{cells}\n        </tr>")

    return headers, "\n".join(rows)


def generate_html(data, skill_name):
    """Generate the complete HTML report."""
    verdict = data.get("verdict", "UNKNOWN")
    passed = data.get("passed", False)
    overall_mean = data.get("overall_mean", 0)
    threshold = data.get("pass_threshold", 3.5)
    total_runs = data.get("total_runs", 0)
    dim_stats = data.get("dimensions", {})
    per_run = data.get("per_run", [])

    verdict_class = "pass" if passed else "fail"
    v_char, _ = indicator(passed)
    o_char, o_cls = indicator(passed)

    dimension_rows = build_dimension_rows(dim_stats, threshold)
    per_run_headers, per_run_rows = build_per_run_rows(per_run, threshold)

    return HTML_TEMPLATE.format(
        skill_name=skill_name,
        eval_date=time.strftime("%Y-%m-%d"),
        total_runs=total_runs,
        verdict=verdict,
        verdict_class=verdict_class,
        verdict_indicator=v_char,
        overall_mean=overall_mean,
        overall_indicator=f'<span class="{o_cls}">{o_char}</span>',
        dimension_rows=dimension_rows,
        per_run_headers=per_run_headers,
        per_run_rows=per_run_rows,
        threshold=threshold,
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate an HTML report from benchmark results"
    )
    parser.add_argument(
        "--results-dir",
        required=True,
        help="Directory containing aggregated results and grade files",
    )
    parser.add_argument(
        "--skill-name",
        required=True,
        help="Name of the skill being evaluated",
    )
    parser.add_argument(
        "--output",
        default="report.html",
        help="Output path for the HTML report (default: report.html)",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.results_dir):
        print(
            f"Error: results directory not found: {args.results_dir}",
            file=sys.stderr,
        )
        sys.exit(1)

    data = load_aggregated(args.results_dir)
    if data is None:
        print(
            "Error: no aggregated results or grade files found in "
            f"{args.results_dir}",
            file=sys.stderr,
        )
        sys.exit(1)

    html = generate_html(data, args.skill_name)

    with open(args.output, "w", encoding="utf-8") as f:
        f.write(html)

    verdict = data.get("verdict", "UNKNOWN")
    print(
        f"Report written to {args.output} — verdict: {verdict}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
